/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background":                "#0A0A0A",
        "surface":                   "#131313",
        "surface-dim":               "#131313",
        "surface-bright":            "#3a3939",
        "surface-container-lowest":  "#0e0e0e",
        "surface-container-low":     "#1c1b1b",
        "surface-container":         "#201f1f",
        "surface-container-high":    "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-variant":           "#353534",
        "surface-tint":              "#c6c6c7",
        "primary":                   "#ffffff",
        "on-primary":                "#2f3131",
        "primary-fixed":             "#e2e2e2",
        "primary-fixed-dim":         "#c6c6c7",
        "on-primary-fixed":          "#1a1c1c",
        "on-primary-fixed-variant":  "#454747",
        "primary-container":         "#2a2a2a",
        "on-primary-container":      "#e5e2e1",
        "inverse-primary":           "#5d5f5f",
        "secondary":                 "#c8c6c5",
        "on-secondary":              "#303030",
        "secondary-container":       "#3a3939",
        "on-secondary-container":    "#e5e2e1",
        "secondary-fixed":           "#e5e2e1",
        "secondary-fixed-dim":       "#c8c6c5",
        "on-secondary-fixed":        "#1b1c1c",
        "on-secondary-fixed-variant":"#474746",
        "tertiary":                  "#ffffff",
        "on-tertiary":               "#2f3131",
        "tertiary-container":        "#2a2a2a",
        "on-tertiary-container":     "#c8c6c5",
        "tertiary-fixed":            "#e2e2e2",
        "tertiary-fixed-dim":        "#c6c6c7",
        "on-tertiary-fixed":         "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        "error":                     "#ffb4ab",
        "on-error":                  "#690005",
        "error-container":           "#7a1010",
        "on-error-container":        "#ffdad6",
        "outline":                   "#8e9192",
        "outline-variant":           "#3a3a3a",
        "on-surface":                "#e5e2e1",
        "on-surface-variant":        "#c4c7c8",
        "on-background":             "#e5e2e1",
        "inverse-surface":           "#e5e2e1",
        "inverse-on-surface":        "#313030",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg":      "0.5rem",
        "xl":      "0.75rem",
        "2xl":     "16px",
        "3xl":     "24px",
        "full":    "9999px",
      },
      spacing: {
        "container-padding-mobile":  "20px",
        "stack-md":                  "24px",
        "base":                      "8px",
        "gutter":                    "16px",
        "container-padding-desktop": "40px",
        "stack-lg":                  "48px",
        "stack-sm":                  "12px",
      },
      fontFamily: {
        "body-lg":           ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "display-lg":        ["Inter", "sans-serif"],
        "headline-md":       ["Inter", "sans-serif"],
        "body-sm":           ["Inter", "sans-serif"],
        "label-caps":        ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg":           ["16px", { lineHeight: "24px",  fontWeight: "400" }],
        "display-lg-mobile": ["26px", { lineHeight: "32px",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg":        ["32px", { lineHeight: "40px",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md":       ["20px", { lineHeight: "28px",  letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm":           ["14px", { lineHeight: "20px",  fontWeight: "400" }],
        "label-caps":        ["12px", { lineHeight: "16px",  letterSpacing: "0.08em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
